import Head from 'next/head'

export default function Product({ product }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="main">
        <section class="breadcrumbs">
          <ul>
            <li>
              <a href="/">Back to home</a>
            </li>
            <li>
              {product.name}
            </li>
          </ul>
        </section>

        <section>
          <h1>{product.name}</h1>
          <img src={product.image_url} alt='' />
          <p>${product.msrp}</p>
          <p>FOR SALE: ${product.sales_price}</p>
          <p>Shipping Price: ${product.shipping_price}</p>
          <p>URL: {product.url}</p>
        </section>

        <pre>
          { JSON.stringify(product, null, 2) }
        </pre>
      </main>
    </>
  )
}

export async function getStaticPaths() {

console.log("!! Paths !! ");
  const resP = await fetch( process.env.NEXT_PUBLIC_SUPABASE_URL + '/rest/v1/products', {
    method: 'GET',
    headers: {
      apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    }
  });

  const products = await resP.json();
  const paths = products.map((product) => (
    { params: { id: JSON.stringify(product.id) } }
  ))

  return {
    paths: paths,
    fallback: 'blocking',
  }
}

export async function getStaticProps({ params }) {
console.log("-- Props -- ");
  const resP = await fetch( process.env.NEXT_PUBLIC_SUPABASE_URL + '/rest/v1/products', {
    method: 'GET',
    headers: {
      apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    }
  });

  const products = await resP.json();
  const product = products.find(product => product.id == params.id)

  return {
    props: {
      product,
    }
  }
}