import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className={styles.description}>
        <p>
          Sorry, the page you are looking for does not exist
        </p>
      </section>
    </>
  )
}
