import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Testing out Some Next.Js stuff</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.section}>
        <h1>Homepage</h1>
        <div className={styles.imgcontainer}>
          <Image src="https://iconfitness-res.cloudinary.com/image/upload/v1670952818/nordictrack.com/cdn/images/catalog/modules/12-06-22-slide_hero_lg-v2.jpg" alt="placeholder" fill />
        </div>
      </section>

    </>
  )
}
